language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
  - composer selfupdate
  - composer require --no-update doctrine/orm:${DOCTRINE_VERSION}

install:
  - composer install --dev --no-interaction --no-progress --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --report=full --standard=PSR2 --encoding=utf-8 src

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email: jasper@nerdsweide.nl
