language: php

php:
  - 7.1
  - 7.2

install:
  - composer install --no-interaction --no-progress --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs --report=full --standard=PSR2 --encoding=utf-8 src

after_script:
  - tests/upload-coverage.sh

notifications:
  email: jasper@future500.nl
